# docker-compose.yml
version: "3.8"
services:
  nginx:
    container_name: simple_marketplace_nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local
  php:
    container_name: simple_marketplace_php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www/html
    networks:
      - local
  npm:
    image: node:13.7
    container_name: simple_marketplace_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
  composer:
    image: composer:2
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - local
  artisan:
    build: ./docker/php
    container_name: simple_marketplace_artisan
    volumes:
      - ./src:/var/www/html
    networks:
      - local
    working_dir: /var/www/html
    entrypoint: ['php', /var/www/html/artisan]
  mysql:
    image: mysql:8.0.27
    container_name: simple_marketplace_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/mysql:/var/lib/mysql
    networks:
      - local
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: simple_marketplace_pma
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 500M
    restart: always
    ports:
      - 8085:80
    networks:
      - local
    expose:
      - 33060:3306

networks:
  local:
    external: true